name: Deno Test

on: [pull_request]

jobs:
  check:
    uses: kakomimasu/kakomimasu.github.io/.github/workflows/dfl-check.yml@main
    with:
      config_file: deno.json
  update-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Install xmllint
        run: |
          sudo apt update
          sudo apt-get install -y libxml2-utils 
      - name: Run xml check
        run: |
          deno run -A --no-check=remote main.ts
          xmllint --format --encode Shift_JIS --output electone-fmt.xml electone.xml
          cp --force electone-fmt.xml electone.xml
          rm electone-fmt.xml
          git add electone.xml && git diff --cached --exit-code
