name: Deno Test

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    uses: kamekyame/gh-actions-test/.github/workflows/dfl-check.yml@main
  update-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run xml check
        run: |
          deno task create
          git add electone.xml && git diff --cached --exit-code
