name: Deno Test

on: [pull_request]

jobs:
  check:
    uses: kamekyame/gh-actions-test/.github/workflows/dfl-check.yml@main
  update-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Install xmllint
        run: |
          sudo apt update
          sudo apt-get install -y libxml2-utils 
      - name: Run xml check
        run: |
          deno run -A --no-check=remote main.ts
          git add electone.xml && git diff --cached --exit-code
