name: create-release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'Release version'

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x 
      - name: Check XML version
        run:
          deno task version-checker ${{ github.event.inputs.version }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y/%m/%d')"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.event.inputs.version }} - ${{ steps.date.outputs.date }}
          tag_name: ${{ github.event.inputs.version }}
          generate_release_notes: true
          files: |
            Electone_EL-xxx.xml
            Electone_ELS-02.xml